name: API and Web Automation workflow

on:
   workflow_dispatch:  # Manual trigger
   push:
    branches: [ "master" ]
   pull_request:
    branches: [ "master" ]


jobs:

  run-api-automation:
  
    runs-on: ubuntu-latest

    steps:

    # download repo
    - uses: actions/checkout@v4

    # setup java
    - name: Set up JDK 11
      uses: actions/setup-java@v4.0.0
      with:
        java-version: '11'
        distribution: 'temurin'

    # install edge browser
    - name: Set up browser Edge
      uses: browser-actions/setup-edge@v1.1.0

    # setup gradlew
    - name: Set up gradlew
      run : chmod +x gradlew

    # Execute gradle task api
    - name: Execute API automation
      run : ./gradlew api

    # Archive test result
    - name: Archive Test Result
      uses: actions/upload-artifact@v3.1.0
      if: always()
      with:
        name: api automation report
        path: report

    # Deploy report to Github Pages
    - name: Deploy report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_DIR: reports

  
  
  
  run-web-automation:
  
    runs-on: ubuntu-latest

    steps:

    # download repo
    - uses: actions/checkout@v4

    # setup java
    - name: Set up JDK 11
      uses: actions/setup-java@v4.0.0
      with:
        java-version: '11'
        distribution: 'temurin'

    # install edge browser
    - name: Set up browser Edge
      uses: browser-actions/setup-edge@v1.1.0

    # setup gradlew
    - name: Set up gradlew
      run : chmod +x gradlew

    # Execute gradle task web
    - name: Execute web automation
      run : ./gradlew web

    # Archive test result
    - name: Archive Test Result
      uses: actions/upload-artifact@v3.1.0
      if: always()
      with:
        name: web automation report
        path: report

    # Deploy report to Github Pages
    - name: Deploy report to GitHub Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3.9.3
      with:
        PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_DIR: report
